### ISSUE TITLE
Inaccurate battery voltage detection accuracy

### ISSUE THREAD

**Issue by 1278043638** [LibreSolar/bms-firmware#30]
During the test, I found that the error of battery 1 was a little large. The voltage measured by the multimeter is 3.83V. How should this be adjusted?

{"rBat_V":22.38,"rBat_A":0.00,"rBat_degC":-58.8,"rSOC_pct":100.0,"rErrorFlags":320,"rBmsState":0,"rCells_V":[3.696,3.826,3.819,3.828,3.829,3.821,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000],"rCellAvg_V":3.803,"rCellMin_V":3.696,"rCellMax_V":3.829,"rBalancingStatus":0}

**Comment by martinjaeger** [comment]
How did you connect the first cell? Did you add two separate wires for GND and C0? If not, you could get a measurement error because the internal power supply current goes through the cell balancing/measurement wire.

I have verified with my hardware and the cell voltages are all very accurate (including the first one). Fluke measurement is same as cell voltage measurement through BMS with deviation of +-1 mV.

**Comment by 1278043638** [comment]
Thank you for your help. After I checked the schematic diagram, I found that I did not connect bat -, which would cause problems in the measurement. I have solved the problem, and the result is very accurate.
