### ISSUE TITLE
BQ769x0-variant with mbed shows wrong current/temperature

### ISSUE THREAD

**Issue by xsider** [LibreSolar/bms-firmware#8]
When compiled for mbed, the BQ769x0-variant shows wrong data in current measurement and temperature measurement (-273°C), this renders the BMS unusable. Fix follows.

**Comment by xsider** [comment]
#10 fixes the problem.

**Comment by martinjaeger** [comment]
Thanks for the bug report and the fix. Already merged it.

FYI: The firmware is soon going to be switched completely to Zephyr in order to make it more clean and easier to maintain (similar to the charge controller firmware). Just need a bit more of testing, but most of the change is already done in the `develop` branch.
